// src/utils/error.codes.js

const ERROR_CODES = {
    // General Errors
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    INVALID_INPUT: 'INVALID_INPUT',

    // Authentication Errors
    AUTH_REQUIRED_FIELDS_MISSING: 'AUTH_REQUIRED_FIELDS_MISSING',
    AUTH_USERNAME_TAKEN: 'AUTH_USERNAME_TAKEN',
    AUTH_EMAIL_REGISTERED: 'AUTH_EMAIL_REGISTERED',
    AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
    AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
    AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
    AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
    AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',

    // Database Errors (có thể chi tiết hơn nếu cần)
    DB_OPERATION_FAILED: 'DB_OPERATION_FAILED',
    DB_RECORD_NOT_FOUND: 'DB_RECORD_NOT_FOUND',

    // ... (Thêm các mã lỗi khác khi cần)
};

module.exports = ERROR_CODES;